### PR TITLE
makes it clear it requires Python 3

### PR DESCRIPTION
**Pull request by mhausenblas**
The current install is not clear about which version of Python to use and it certainly does not work under Python 2.7.10, so would be great to clarify this.

### CODE REVIEW

**Comment by vogxn** [comment]
@mhausenblas I tested this on 2.7.12. Did your installation fail? Could you share the pip install log?

**Comment by mhausenblas** [comment]
Yes, it failed. And it worked flawlessly with Python 3. Otherwise I wouldn't have sent in the PR ;)

So, I've got:

```
$ python -V
Python 2.7.10
```

And the relevant part of the install, where it fails:

```
...Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-T7nHf0-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by vogxn** [comment]
Thanks Michael! I positively want to get this working on both python2 and python3. I just installed 2.7.10 and tested the package. My log is below. 

```
(test-kube-shell) ➜  kube-shell git:(master) ✗ python
Python 2.7.10 (default, Jul  1 2017, 23:32:39)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
(test-kube-shell) ➜  kube-shell git:(master) ✗ pip install kube-shell
Collecting kube-shell
  Downloading kube-shell-0.0.17.tar.gz
Collecting prompt-toolkit<1.1.0,>=1.0.0 (from kube-shell)
  Using cached prompt_toolkit-1.0.14-py2-none-any.whl
Collecting Pygments<3.0.0,>=2.1.3 (from kube-shell)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting fuzzyfinder>=1.0.0 (from kube-shell)
  Using cached fuzzyfinder-1.0.0-py2.py3-none-any.whl
Collecting click<7.0,>=4.0 (from kube-shell)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting kubernetes>=0.10.0 (from kube-shell)
  Using cached kubernetes-2.0.0-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt-toolkit<1.1.0,>=1.0.0->kube-shell)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<1.1.0,>=1.0.0->kube-shell)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting websocket-client (from kubernetes>=0.10.0->kube-shell)
  Using cached websocket_client-0.44.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /Users/tsp/.pyenv/versions/2.7.10/envs/test-kube-shell/lib/python2.7/site-packages (from kubernetes>=0.10.0->kube-shell)
Collecting oauth2client (from kubernetes>=0.10.0->kube-shell)
  Using cached oauth2client-4.1.2-py2.py3-none-any.whl
Collecting urllib3!=1.21 (from kubernetes>=0.10.0->kube-shell)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting pyyaml (from kubernetes>=0.10.0->kube-shell)
Collecting ipaddress (from kubernetes>=0.10.0->kube-shell)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting python-dateutil (from kubernetes>=0.10.0->kube-shell)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting certifi (from kubernetes>=0.10.0->kube-shell)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client->kubernetes>=0.10.0->kube-shell)
  Using cached pyasn1_modules-0.0.9-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client->kubernetes>=0.10.0->kube-shell)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client->kubernetes>=0.10.0->kube-shell)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client->kubernetes>=0.10.0->kube-shell)
Building wheels for collected packages: kube-shell
  Running setup.py bdist_wheel for kube-shell ... done
  Stored in directory: /Users/tsp/Library/Caches/pip/wheels/d1/3a/88/d3a05687d10c56d83b46a09d6efc269442ae21dbbe0b7c1105
Successfully built kube-shell
Installing collected packages: six, wcwidth, prompt-toolkit, Pygments, fuzzyfinder, click, websocket-client, pyasn1, pyasn1-modules, rsa, httplib2, oauth2client, urllib3, pyyaml, ipaddress, python-dateutil, certifi, kubernetes, kube-shell
Successfully installed Pygments-2.2.0 certifi-2017.4.17 click-6.7 fuzzyfinder-1.0.0 httplib2-0.10.3 ipaddress-1.0.18 kube-shell-0.0.17 kubernetes-2.0.0 oauth2client-4.1.2 prompt-toolkit-1.0.14 pyasn1-0.2.3 pyasn1-modules-0.0.9 python-dateutil-2.6.0 pyyaml-3.12 rsa-3.4.2 six-1.10.0 urllib3-1.21.1 wcwidth-0.1.7 websocket-client-0.44.0
(test-kube-shell) ➜  kube-shell git:(master) ✗ kube-shell
kube-shell> kubectl get node
NAME      STATUS    AGE       VERSION
worker0   Ready     14h       v1.6.1
worker1   Ready     14h       v1.6.1
kube-shell>
```

Could you try the installer in a `virtualenv` created from your global 2.7.10 python?

**Comment by mhausenblas** [comment]
Turns out there's something b0rked with my Python setup. Gotta luv the mess Apple has there with both Python and Ruby on macOS. I'll revoke this PR here but I do do encourage you to be explicit about the prerequisites by listing the Python versions tested/supported.

**Pull request closed without merging**
